# Generated by Django 2.1.7 on 2020-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_category', models.CharField(default='', max_length=50)),
                ('sub_product_category', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='description comes here', max_length=255)),
                ('published_date', models.DateField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='products/images')),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
